name: nocode_
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_design: ^0.0.11-pre+1
  flutter_design_viewer: ^0.0.11-pre+1
  flutter_feather_icons: ^2.0.0+1
  ionicons: ^0.1.2
  url_strategy: ^0.2.0
  flutter_hooks: ^0.18.2
  hooks_riverpod: ^1.0.3
  flutter_staggered_grid_view: ^0.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  flutter_design_codegen: ^0.0.11-pre+1
  build_runner: ^2.1.7

flutter:

  uses-material-design: true